### ISSUE TITLE
Add support for the Unity Desktop Environment 

### ISSUE THREAD

**Issue by sceptic30** [Fullaxx/ubuntu-desktop#3]
Would be nice to use the Unity Desktop Environment, and not openbox that looks outdated nowadays.

**Comment by Fullaxx** [comment]
Unity branch has been created and updated:

https://github.com/Fullaxx/ubuntu-desktop/tree/unity

**Comment by Fullaxx** [comment]
docker pull fullaxx/ubuntu-desktop:unity
should work
